name: Bazaar
main: me.math3w.bazaar.BazaarPlugin
version: 1.0
author: _Math3w_
api-version: 1.21
depend:
  - Vault
commands:
  vanbaophieu:
    description: Opens bazaar menu
    permission: bazaar.open
  vanbaophieuedit:
    description: Opens edit menu
    permission: bazaar.edit
  category:
    description: Manage bazaar categories
    permission: bazaar.admin
  stock:
    description: Manage stocks
    permission: bazaar.admin
permissions:
  bazaar.open:
    default: true
  bazaar.edit:
    default: op
  bazaar.admin:
    default: op